-- 0001_init.sql — Persona Hub MVP core schema (PostgreSQL 16 + pgvector)
-- IDs: text, prefixed ULIDs generated by the app (usr_, per_, fct_, con_, log_, itv_, exp_, ses_, sug_ ...).
-- Timestamps: timestamptz (UTC on the wire, ISO 8601).
-- Fact bodies: normal -> body_plain; sensitive/private -> body_enc (AES-256-GCM, encrypted in the app, never in SQL).

CREATE EXTENSION IF NOT EXISTS vector;

-- ---------------------------------------------------------------------------
-- helpers
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END $$;

-- ---------------------------------------------------------------------------
-- users / identities
-- ---------------------------------------------------------------------------
CREATE TABLE users (
  id            text PRIMARY KEY CHECK (id ~ '^usr_'),
  display_name  text NOT NULL DEFAULT '',
  plan          text NOT NULL DEFAULT 'free' CHECK (plan IN ('free','pro')),
  consents      jsonb NOT NULL DEFAULT '{"terms":true,"sensitive_data":false,"marketing":false}'::jsonb
                CHECK (jsonb_typeof(consents) = 'object'),
  -- Wrapped per-user data key (KMS Encrypt output). NULL until the first sensitive fact.
  dek_wrapped   bytea,
  dek_key_id    text,        -- KMS key ARN/alias version used to wrap dek_wrapped
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  deleted_at    timestamptz,  -- DELETE /me; purge job hard-deletes within 30 days
  CHECK ((dek_wrapped IS NULL) = (dek_key_id IS NULL))
);
CREATE INDEX users_deleted_at_idx ON users (deleted_at) WHERE deleted_at IS NOT NULL;
CREATE TRIGGER users_updated_at BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE identities (
  provider    text NOT NULL CHECK (provider IN ('kakao','apple','google','dev')),
  subject     text NOT NULL,
  user_id     text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (provider, subject)          -- TS Identity.key = `${provider}:${subject}`
);
CREATE INDEX identities_user_idx ON identities (user_id);

-- ---------------------------------------------------------------------------
-- personas
-- ---------------------------------------------------------------------------
CREATE TABLE personas (
  id            text PRIMARY KEY CHECK (id ~ '^per_'),
  user_id       text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name          text NOT NULL CHECK (char_length(name) BETWEEN 1 AND 100),
  icon          text NOT NULL DEFAULT '',
  summary       text NOT NULL DEFAULT '',
  instructions  text NOT NULL DEFAULT '',
  archived      boolean NOT NULL DEFAULT false,
  version       integer NOT NULL DEFAULT 1 CHECK (version >= 1),
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (id, user_id)   -- target for composite FKs (facts/suggestions ownership)
);
-- per-user limit (free 3 / pro 10, hard 10) is enforced in the app (needs plan + 403 plan_limit_reached)
CREATE INDEX personas_user_idx ON personas (user_id, archived, updated_at DESC);
CREATE TRIGGER personas_updated_at BEFORE UPDATE ON personas FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- facts  (hard delete only — no deleted_at)
-- ---------------------------------------------------------------------------
CREATE TABLE facts (
  id           text PRIMARY KEY CHECK (id ~ '^fct_'),
  persona_id   text NOT NULL,
  user_id      text NOT NULL,   -- denormalised owner for RLS / purge / per-user DEK lookup
  category     text NOT NULL CHECK (category IN ('profile','work','interest','health','finance','preference','other')),
  sensitivity  text NOT NULL CHECK (sensitivity IN ('normal','sensitive','private')),
  source       text NOT NULL CHECK (source IN ('manual','interview','ai_suggestion','import')),
  body_plain   text,            -- normal only
  body_enc     bytea,           -- sensitive/private: nonce(12) || ciphertext || tag(16)
  key_id       text,            -- which wrapped DEK (users.dek_key_id at write time) encrypted body_enc
  embedding    vector(1536),    -- NULL for private (never searchable); see README re: sensitive
  version      integer NOT NULL DEFAULT 1 CHECK (version >= 1),
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (persona_id, user_id) REFERENCES personas (id, user_id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT facts_body_storage CHECK (
    (sensitivity = 'normal' AND body_plain IS NOT NULL AND body_enc IS NULL AND key_id IS NULL)
    OR
    (sensitivity IN ('sensitive','private') AND body_plain IS NULL AND body_enc IS NOT NULL AND key_id IS NOT NULL)
  ),
  CONSTRAINT facts_body_len CHECK (body_plain IS NULL OR char_length(body_plain) BETWEEN 1 AND 500),
  CONSTRAINT facts_private_no_embedding CHECK (sensitivity <> 'private' OR embedding IS NULL)
);
-- persona detail / MCP get_persona: facts by persona filtered by sensitivity
CREATE INDEX facts_persona_sens_idx ON facts (persona_id, sensitivity, updated_at DESC);
CREATE INDEX facts_user_idx ON facts (user_id);
-- search_facts: ANN over embeddings (post-filtered by persona_id = ANY(...) AND sensitivity rank)
CREATE INDEX facts_embedding_hnsw ON facts USING hnsw (embedding vector_cosine_ops) WHERE embedding IS NOT NULL;
CREATE TRIGGER facts_updated_at BEFORE UPDATE ON facts FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- OAuth (authorization server for AI clients) — DCR + PKCE
-- ---------------------------------------------------------------------------
CREATE TABLE oauth_clients (
  client_id                  text PRIMARY KEY,
  client_name                text NOT NULL,
  redirect_uris              text[] NOT NULL CHECK (cardinality(redirect_uris) >= 1),
  token_endpoint_auth_method text NOT NULL DEFAULT 'none' CHECK (token_endpoint_auth_method IN ('none','client_secret_basic','client_secret_post')),
  client_secret_hash         text,
  verified                   boolean NOT NULL DEFAULT false,   -- known clients (Claude, ChatGPT) get a badge
  metadata                   jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at                 timestamptz NOT NULL DEFAULT now(),
  updated_at                 timestamptz NOT NULL DEFAULT now()
);
CREATE TRIGGER oauth_clients_updated_at BEFORE UPDATE ON oauth_clients FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- connections (source of truth for per-connection scope; checked on every MCP call)
-- ---------------------------------------------------------------------------
CREATE TABLE connections (
  id                text PRIMARY KEY CHECK (id ~ '^con_'),
  user_id           text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  client_id         text NOT NULL REFERENCES oauth_clients(client_id),
  client_name       text NOT NULL,              -- snapshot shown in the app
  persona_ids       text[] NOT NULL DEFAULT '{}',  -- not FK-able; app prunes on persona delete
  max_sensitivity   text NOT NULL DEFAULT 'normal' CHECK (max_sensitivity IN ('normal','sensitive')),
  version           integer NOT NULL DEFAULT 1 CHECK (version >= 1),
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  revoked_at        timestamptz,
  last_accessed_at  timestamptz,
  CHECK (array_position(persona_ids, NULL) IS NULL)
);
CREATE INDEX connections_user_idx ON connections (user_id, created_at DESC);
CREATE INDEX connections_active_idx ON connections (user_id) WHERE revoked_at IS NULL;
CREATE INDEX connections_client_idx ON connections (client_id);
CREATE INDEX connections_persona_ids_gin ON connections USING gin (persona_ids);  -- prune on persona delete
CREATE TRIGGER connections_updated_at BEFORE UPDATE ON connections FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE oauth_codes (
  code_hash              text PRIMARY KEY,   -- sha256(code)
  client_id              text NOT NULL REFERENCES oauth_clients(client_id) ON DELETE CASCADE,
  user_id                text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  connection_id          text NOT NULL REFERENCES connections(id) ON DELETE CASCADE,
  redirect_uri           text NOT NULL,
  code_challenge         text NOT NULL,
  code_challenge_method  text NOT NULL DEFAULT 'S256' CHECK (code_challenge_method = 'S256'),
  scope                  text NOT NULL DEFAULT '',
  resource               text,
  expires_at             timestamptz NOT NULL,
  used_at                timestamptz,
  created_at             timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX oauth_codes_expires_idx ON oauth_codes (expires_at);
CREATE INDEX oauth_codes_user_idx ON oauth_codes (user_id);

CREATE TABLE oauth_tokens (
  token_hash     text PRIMARY KEY,           -- sha256(token)
  kind           text NOT NULL CHECK (kind IN ('access','refresh')),
  connection_id  text NOT NULL REFERENCES connections(id) ON DELETE CASCADE,
  user_id        text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  client_id      text NOT NULL REFERENCES oauth_clients(client_id) ON DELETE CASCADE,
  family_id      text NOT NULL,              -- refresh rotation family; reuse => revoke whole connection
  used           boolean NOT NULL DEFAULT false,
  expires_at     timestamptz NOT NULL,       -- access 1h, refresh 30d
  revoked_at     timestamptz,
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX oauth_tokens_connection_idx ON oauth_tokens (connection_id);
CREATE INDEX oauth_tokens_family_idx ON oauth_tokens (family_id);
CREATE INDEX oauth_tokens_user_idx ON oauth_tokens (user_id);
CREATE INDEX oauth_tokens_expires_idx ON oauth_tokens (expires_at);

-- ---------------------------------------------------------------------------
-- app auth (mobile): sessions + rotating refresh tokens
-- ---------------------------------------------------------------------------
CREATE TABLE auth_sessions (
  id          text PRIMARY KEY,               -- family id == `sid` claim
  user_id     text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at  timestamptz NOT NULL DEFAULT now(),
  revoked_at  timestamptz
);
CREATE INDEX auth_sessions_user_idx ON auth_sessions (user_id) WHERE revoked_at IS NULL;

CREATE TABLE refresh_tokens (
  hash        text PRIMARY KEY,               -- sha256(refresh token)
  family_id   text NOT NULL REFERENCES auth_sessions(id) ON DELETE CASCADE,
  user_id     text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  expires_at  timestamptz NOT NULL,           -- TS: epoch ms number
  used        boolean NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX refresh_tokens_family_idx ON refresh_tokens (family_id);
CREATE INDEX refresh_tokens_user_idx ON refresh_tokens (user_id);
CREATE INDEX refresh_tokens_expires_idx ON refresh_tokens (expires_at);

-- ---------------------------------------------------------------------------
-- access_logs — partitioned by month, 1-year retention
-- ---------------------------------------------------------------------------
CREATE TABLE access_logs (
  id             text NOT NULL CHECK (id ~ '^log_'),
  user_id        text NOT NULL,              -- owner (RLS + app "who saw what" screen); no FK on partitioned child rows kept simple
  connection_id  text NOT NULL,
  client_name    text NOT NULL,
  tool           text NOT NULL CHECK (tool IN ('list_personas','get_persona','search_facts','suggest_fact')),
  persona_ids    text[] NOT NULL DEFAULT '{}',
  fact_ids       text[] NOT NULL DEFAULT '{}',
  query_text     text,                        -- search_facts input; NULLed after 30 days
  latency_ms     integer NOT NULL DEFAULT 0 CHECK (latency_ms >= 0),
  created_at     timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id, created_at),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (connection_id) REFERENCES connections(id) ON DELETE CASCADE
) PARTITION BY RANGE (created_at);
CREATE INDEX access_logs_connection_idx ON access_logs (connection_id, created_at DESC);
CREATE INDEX access_logs_user_idx ON access_logs (user_id, created_at DESC);
CREATE INDEX access_logs_query_purge_idx ON access_logs (created_at) WHERE query_text IS NOT NULL;
CREATE TABLE access_logs_default PARTITION OF access_logs DEFAULT;

-- ---------------------------------------------------------------------------
-- interviews / exports
-- ---------------------------------------------------------------------------
CREATE TABLE interviews (
  id           text PRIMARY KEY CHECK (id ~ '^itv_'),
  user_id      text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  template_id  text NOT NULL,
  persona_id   text REFERENCES personas(id) ON DELETE SET NULL,
  status       text NOT NULL DEFAULT 'in_progress' CHECK (status IN ('in_progress','extracted','committed')),
  answers      jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(answers) = 'array'),
  candidates   jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(candidates) = 'array'),
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX interviews_user_idx ON interviews (user_id, created_at DESC);
CREATE TRIGGER interviews_updated_at BEFORE UPDATE ON interviews FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE exports (
  id          text PRIMARY KEY CHECK (id ~ '^exp_'),
  user_id     text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  status      text NOT NULL DEFAULT 'ready' CHECK (status IN ('pending','ready','failed','expired')),
  data        jsonb,                          -- snapshot (MVP); later: object-storage key
  created_at  timestamptz NOT NULL DEFAULT now(),
  expires_at  timestamptz NOT NULL DEFAULT now() + interval '7 days'
);
CREATE INDEX exports_user_idx ON exports (user_id, created_at DESC);
CREATE INDEX exports_expires_idx ON exports (expires_at);

-- ---------------------------------------------------------------------------
-- idempotency (24h)
-- ---------------------------------------------------------------------------
CREATE TABLE idempotency_keys (
  user_id          text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  key              uuid NOT NULL,
  method           text NOT NULL,
  path             text NOT NULL,
  request_hash     text NOT NULL,             -- sha256 of body; mismatch on reuse => 422/409
  response_status  integer,
  response_body    jsonb,                     -- NULL while in flight
  created_at       timestamptz NOT NULL DEFAULT now(),
  expires_at       timestamptz NOT NULL DEFAULT now() + interval '24 hours',
  PRIMARY KEY (user_id, key)
);
CREATE INDEX idempotency_keys_expires_idx ON idempotency_keys (expires_at);

-- ---------------------------------------------------------------------------
-- suggestions (v1: suggest_fact inbox)
-- ---------------------------------------------------------------------------
CREATE TABLE suggestions (
  id             text PRIMARY KEY CHECK (id ~ '^sug_'),
  user_id        text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  connection_id  text NOT NULL REFERENCES connections(id) ON DELETE CASCADE,
  persona_id     text NOT NULL,
  fact_id        text REFERENCES facts(id) ON DELETE SET NULL,
  op             text NOT NULL CHECK (op IN ('add','update','remove')),
  payload        jsonb NOT NULL DEFAULT '{}'::jsonb,   -- {body, reason}; body may be sensitive -> keep short-lived
  status         text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected','expired')),
  decided_at     timestamptz,
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  FOREIGN KEY (persona_id, user_id) REFERENCES personas (id, user_id) ON DELETE CASCADE,
  CHECK ((status = 'pending') = (decided_at IS NULL))
);
CREATE INDEX suggestions_user_pending_idx ON suggestions (user_id, created_at DESC) WHERE status = 'pending';
CREATE INDEX suggestions_connection_idx ON suggestions (connection_id);
CREATE TRIGGER suggestions_updated_at BEFORE UPDATE ON suggestions FOR EACH ROW EXECUTE FUNCTION set_updated_at();
